/**
 * Agent State for Medical Agent Graph
 * 
 * This interface defines the shared state that flows between AI agents
 * in the LangGraph workflow.
 */
export interface AgentState {
    /** Raw transcript from speech-to-text */
    transcript: string; //input

    /** SOAP notes generated by Scribe Agent */
    //Output từ Scribe
    soap: {
        subjective: string;  // Patient's symptoms, history
        objective: string;   // Physical examination findings
        assessment: string;  // Diagnosis
        plan: string;        // Treatment plan
    };

    /** ICD-10 codes suggested by ICD Agent */
    icdCodes: string[]; // Output từ ICD Agent

    /** Medical advice from Expert Agent (RAG-based) */
    medicalAdvice: string; // Output từ Expert Agent

    /** References from medical knowledge base */
    references: string[]; // Source từ RAG
}
